### ISSUE TITLE
swap_retry=0

### ISSUE THREAD

**Issue by CaucherWang** [Visual-Computing/DynamicExplorationGraph#1]
`deglib_build_bench.cpp` line 18,19
you set `swap_tries` = 0, which forbids the edge optimization in your paper.
But according to the results of your paper (Figure 9), the edge optimization matters in search performance.
Why do you forbid it in the benchmark? It is not good for DEG.

**Comment by Neiko2002** [comment]
Thank you for reaching out. The settings in the deglib_build_bench.cpp file are for reproducing Figures 4 and 5 in the paper. Since the dynamic edge optimization scheme (Alg. 5) can run infinitely many times, we had to balance the construction time and search quality. Therefore, the edge optimization algorithm 4 is called only a few times from the last line of the graph expansion algorithm (Alg. 3), but no additional swaps are made with Algorithm 5 (`swap_tries = 0` disables Alg 5).

If there is no time constraint, the parameters `swap_tries` and `additional_swap_tries` can be increased to perform additional edge optimization attempts (with Alg. 5) and further increase the search efficiency of the DEG. 

Figure 9 shows the search quality if you just run the graph expansion algorithm (Alg. 3) without its last line, which calls the edge optimization algorithm 4 on some of the newly created edges. Nevertheless is your observation valuable and we should have done a better job in section 7.2 to describe why Alg 5 was not used (`swap_tries = 0`) in most of our experiments.

**Comment by CaucherWang** [comment]
Thank you for your patient explanation! I have a better understanding of your work now.
BTW, a small question about Table 1 in your paper. Why do you say Yes for the search reachability of HNSW? In your expr. results, on Glove datasets, some points' in-degree are 0, and so they cannot be reached unless they are the entry point. I think HNSW doesn't have search reachability.

**Comment by Neiko2002** [comment]
You are right, this is a mistake. In fact, Table 12 shows that the search reachability of HNSW for the Enron and GloVe dataset is less than 100%. Thank you for pointing this out.

The `min in-degree` is not a very good indicator of HNSW search reachability, since it starts an ANN search from the top layer and could point a well connected vertex at layer 1 to a source vertex (a vertex with an in-degree of 0) at layer 0. This source vertex would therefore be reachable in an ANN search (from the level above), but unreachable in an exploratory search.

**Comment by CaucherWang** [comment]
OK! Nice work, a large progress in graph-based ANNS.
