### ISSUE TITLE
When will DEG supports the vertex deletion operation?

### ISSUE THREAD

**Issue by ciuji** [Visual-Computing/DynamicExplorationGraph#2]
Thanks for your inspiring work with many great graph properties!
I noticed that the authors left the fully dynamic graphs and dynamic datasets as the future work. And I am wondering when will you release the next version? Soon or in a few months?
Conceptually, I thought for handling deletion, DEG just need to replace the d edges with d/2 new edges. And the Algorithm 4&5 can be applied regularly to maintain the search performance.
Or maybe the authors are designing some totally different deletion strategies for DEG?

Thanks again for the fantastic work!

**Comment by Neiko2002** [comment]
Conceptually, you are right about how to handle the deletion:
- Select the vertex v to be deleted. 
- Remove all d edges of vertex v. 
- Connect its formerly adjacent vertices with d/2 new edges. 
- Remove vertex v. 
- Apply Algorithm 4 to all new edges. 

A naive implementation of this algorithm might disconnect the graph, so our version is a bit more elaborate. There are also situations where you cannot add the d/2 new edges to the formerly adjacent vertices because they are already well connected.  At the moment, we just have a proof of concept written in [EvenRegularGraphDesigner.java](https://github.com/Visual-Computing/DynamicExplorationGraph/blob/main/java/deg-reference/src/main/java/com/vc/deg/ref/designer/EvenRegularGraphDesigner.java#L696). In upcoming work, we will compare the Cpp adaptation of this algorithm to several other graphs using a new testing protocol for dynamic datasets.

**Comment by ciuji** [comment]
Thanks for your explanation!
The graph deletion is a challenging problem, and I thought DEG has a great potentiality to solve it and provide many inspiring insights.
Looking forward for your coming works! Good Luck!
